# Generated by Django 4.0.5 on 2022-06-06 16:44

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('nomeempresa', models.CharField(max_length=65)),
                ('cargo', models.CharField(max_length=65)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=65)),
                ('razao_social', models.CharField(max_length=65)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=65)),
                ('site', models.CharField(max_length=65)),
                ('endereco', models.CharField(max_length=65)),
                ('pais_sede', models.CharField(max_length=65)),
                ('n_funcionarios', models.IntegerField()),
                ('setor', models.CharField(choices=[('Primário', 'Primário'), ('Secundário', 'Secundário'), ('Terciário', 'Terciário')], max_length=65)),
                ('categoria', models.CharField(max_length=120)),
                ('capital', models.CharField(choices=[('Privado', 'Privado'), ('Público', 'Público'), ('Misto', 'Misto')], max_length=65)),
                ('abrangencia', models.CharField(choices=[('Municipal', 'Municipal'), ('Regional', 'Regional'), ('Estadual', 'Estadual'), ('Nacional', 'Nacional'), ('Multinacional', 'Multinacional')], max_length=65)),
            ],
        ),
    ]
