# Generated by Django 4.0.3 on 2022-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.IntegerField(max_length=14)),
                ('telefone', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('site', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=30)),
                ('pais_sede', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Dados_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_funcionarios', models.IntegerField(max_length=10)),
                ('setor', models.CharField(choices=[('Primário', 'Primário'), ('Secundário', 'Secundário'), ('Terciário', 'Terciário')], max_length=15)),
                ('categoria', models.CharField(max_length=120)),
                ('capital', models.CharField(choices=[('Privado', 'Privado'), ('Público', 'Público'), ('Misto', 'Misto')], max_length=15)),
                ('abrangencia', models.CharField(choices=[('Municipal', 'Municipal'), ('Regional', 'Regional'), ('Estadual', 'Estadual'), ('Nacional', 'Nacional'), ('Multinacional', 'Multinacional')], max_length=25)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifier.cadastro_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=25)),
                ('telefone', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('nomeempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifier.cadastro_empresa')),
            ],
        ),
    ]
