# Generated by Django 4.0.5 on 2022-06-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_contato',
            old_name='cargo',
            new_name='cargo_contato',
        ),
        migrations.RenameField(
            model_name='cadastro_contato',
            old_name='email',
            new_name='email_contato',
        ),
        migrations.RenameField(
            model_name='cadastro_contato',
            old_name='nome',
            new_name='nome_contato',
        ),
        migrations.RenameField(
            model_name='cadastro_contato',
            old_name='nomeempresa',
            new_name='nome_empresa_contato',
        ),
        migrations.RenameField(
            model_name='cadastro_empresa',
            old_name='email',
            new_name='email_empresa',
        ),
        migrations.RemoveField(
            model_name='cadastro_contato',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cadastro_empresa',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cadastro_contato',
            name='id_empresa_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Qualifier.cadastro_empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro_contato',
            name='telefone_contato',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro_empresa',
            name='telefone_empresa',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
