# Generated by Django 4.0.3 on 2022-04-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifier', '0002_alter_cadastro_contato_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_contato',
            name='nomeempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifier.cadastro_empresa', to_field='nome_fantasia'),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro_empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dados_empresa',
            name='cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifier.cadastro_empresa', to_field='cnpj'),
        ),
    ]
