# Generated by Django 4.0.3 on 2022-04-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifier', '0003_alter_cadastro_contato_nomeempresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_contato',
            name='nomeempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Qualifier.cadastro_empresa', to_field='nome_fantasia'),
        ),
        migrations.AlterField(
            model_name='dados_empresa',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
    ]
