# Generated by Django 4.0.3 on 2022-04-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifier', '0005_alter_dados_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
