# Generated by Django 4.0.3 on 2022-04-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifier', '0006_alter_dados_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_contato',
            name='nomeempresa',
            field=models.CharField(max_length=50),
        ),
    ]
